import type { Product } from "./types";

const img = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=800&q=80`;

export const PRODUCTS: Product[] = [
  {
    id: "p-001",
    name: "Aurora Merino Overcoat",
    brand: "Northline",
    category: "Outerwear",
    price: 289,
    originalPrice: 360,
    rating: 4.8,
    reviews: 412,
    image: img("photo-1434389677669-e08b4cac3105"),
    colors: ["Camel", "Slate", "Black"],
    sizes: ["S", "M", "L", "XL"],
    tags: ["winter", "formal", "wool"],
    description:
      "A tailored merino-blend overcoat with a soft drape and structured shoulder. Cut for layering over knitwear without losing its line.",
    inStock: true,
  },
  {
    id: "p-002",
    name: "Vector Runner 2",
    brand: "Kadence",
    category: "Footwear",
    price: 148,
    rating: 4.6,
    reviews: 1289,
    image: img("photo-1542291026-7eec264c27ff"),
    colors: ["Crimson", "White", "Navy"],
    sizes: ["7", "8", "9", "10", "11"],
    tags: ["sneakers", "everyday", "sport"],
    description:
      "Responsive foam midsole with a knit upper engineered for daily mileage and street wear alike.",
    inStock: true,
  },
  {
    id: "p-003",
    name: "Studio ANC Headphones",
    brand: "Loft Audio",
    category: "Electronics",
    price: 249,
    originalPrice: 299,
    rating: 4.7,
    reviews: 934,
    image: img("photo-1505740420928-5e560c06d30e"),
    colors: ["Graphite", "Ivory"],
    sizes: ["One size"],
    tags: ["audio", "travel", "work"],
    description:
      "Adaptive noise cancellation, 40-hour battery, and a memory-foam headband tuned for long sessions.",
    inStock: true,
  },
  {
    id: "p-004",
    name: "Meridian Automatic Watch",
    brand: "Halden",
    category: "Accessories",
    price: 420,
    rating: 4.9,
    reviews: 208,
    image: img("photo-1523275335684-37898b6baf30"),
    colors: ["Steel", "Rose Gold"],
    sizes: ["38mm", "42mm"],
    tags: ["formal", "gift", "premium"],
    description:
      "Sapphire crystal over a 42-hour automatic movement, finished with a brushed steel bracelet.",
    inStock: true,
  },
  {
    id: "p-005",
    name: "Everyday Heavy Tee",
    brand: "Basework",
    category: "Tops",
    price: 42,
    rating: 4.4,
    reviews: 2310,
    image: img("photo-1521572163474-6864f9cf17ab"),
    colors: ["White", "Sand", "Black"],
    sizes: ["XS", "S", "M", "L", "XL"],
    tags: ["basics", "cotton", "summer"],
    description: "260gsm combed cotton with a boxy fit that holds shape after repeated washing.",
    inStock: true,
  },
  {
    id: "p-006",
    name: "Transit Commuter Pack",
    brand: "Cargo Lab",
    category: "Bags",
    price: 165,
    rating: 4.5,
    reviews: 671,
    image: img("photo-1553062407-98eeb64c6a62"),
    colors: ["Slate", "Olive"],
    sizes: ["22L"],
    tags: ["work", "travel", "waterproof"],
    description:
      "Weatherproof recycled shell, padded 16-inch laptop sleeve, and a magnetic quick-access lid.",
    inStock: true,
  },
  {
    id: "p-007",
    name: "Pulse Smartwatch S3",
    brand: "Kadence",
    category: "Electronics",
    price: 199,
    originalPrice: 239,
    rating: 4.3,
    reviews: 1502,
    image: img("photo-1546868871-7041f2a55e12"),
    colors: ["Midnight", "Silver"],
    sizes: ["41mm", "45mm"],
    tags: ["fitness", "tech", "gift"],
    description: "Continuous heart-rate, sleep staging, and a 7-day battery in an aluminium case.",
    inStock: true,
  },
  {
    id: "p-008",
    name: "Court Leather Sneaker",
    brand: "Northline",
    category: "Footwear",
    price: 132,
    rating: 4.5,
    reviews: 489,
    image: img("photo-1560769629-975ec94e6a86"),
    colors: ["White", "Bone"],
    sizes: ["7", "8", "9", "10", "11", "12"],
    tags: ["smart-casual", "leather"],
    description: "Full-grain leather upper on a low-profile cupsole. Dresses up or down easily.",
    inStock: false,
  },
  {
    id: "p-009",
    name: "Field Optic Sunglasses",
    brand: "Halden",
    category: "Accessories",
    price: 118,
    rating: 4.2,
    reviews: 322,
    image: img("photo-1511499767150-a48a237f0083"),
    colors: ["Tortoise", "Black"],
    sizes: ["One size"],
    tags: ["summer", "travel"],
    description: "Polarised lenses with an acetate frame and adjustable titanium temple tips.",
    inStock: true,
  },
  {
    id: "p-010",
    name: "Frame Compact Camera",
    brand: "Loft Audio",
    category: "Electronics",
    price: 640,
    rating: 4.8,
    reviews: 154,
    image: img("photo-1526170375885-4d8ecf77b99f"),
    colors: ["Black", "Silver"],
    sizes: ["Body only"],
    tags: ["creator", "premium", "travel"],
    description: "24MP APS-C sensor in a pocketable body with a fast fixed 28mm equivalent lens.",
    inStock: true,
  },
  {
    id: "p-011",
    name: "Loft Ribbed Knit",
    brand: "Basework",
    category: "Tops",
    price: 96,
    rating: 4.6,
    reviews: 388,
    image: img("photo-1576566588028-4147f3842f27"),
    colors: ["Ecru", "Forest", "Charcoal"],
    sizes: ["S", "M", "L"],
    tags: ["autumn", "layering"],
    description: "Fine-gauge ribbed knit with a relaxed crew neck, spun from recycled cotton.",
    inStock: true,
  },
  {
    id: "p-012",
    name: "Trail Insulated Jacket",
    brand: "Cargo Lab",
    category: "Outerwear",
    price: 224,
    originalPrice: 275,
    rating: 4.7,
    reviews: 596,
    image: img("photo-1551028719-00167b16eac5"),
    colors: ["Ink", "Rust"],
    sizes: ["S", "M", "L", "XL"],
    tags: ["winter", "outdoor", "packable"],
    description: "Recycled synthetic fill rated to -8°C, packable into its own chest pocket.",
    inStock: true,
  },
];

export const CATEGORIES = Array.from(new Set(PRODUCTS.map((p) => p.category))).sort();
export const BRANDS = Array.from(new Set(PRODUCTS.map((p) => p.brand))).sort();

export function pick(ids: string[]): Product[] {
  return ids.map((id) => PRODUCTS.find((p) => p.id === id)!).filter(Boolean);
}
